name: train-my-model
on: [push]
jobs:
  run:
     runs-on: [ubuntu-latest]
     container: docker://dvcorg/cml-py3:latest
     steps:
        - uses: actions/checkout@v2
        - name: cml_run
          env:
              REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              dvc repro
              dvc metrics diff --show-md master > scores.json
              
